### ISSUE TITLE
Audio Equalizer & Video Adjust

### ISSUE THREAD

**Issue by subh-kundu** [mfkl/libvlcsharp-samples#155]
### Generic information
LibVLCSharp version : 3.6.1
project used : WinForms x64
.net version : 4.5.0
language : C#
OS : Windows 11 x64

how can i set audio equalizer, any example 
`videoView1.MediaPlayer.SetEqualizer `

or
how to pass value slider to adjust brightness, contrast, hue colors
`videoView1.MediaPlayer.AdjustInt(VideoAdjustOption.Hue)`

**Comment by mfkl** [comment]
Hi,

For support, please use stackoverflow or discord. See you there

**Comment by subh-kundu** [comment]
Hi,
I'm follow your steps, some help for me but I've a question how to send command runtime. such as change visualization. like click to scope to spectrometer.

this code only works at loading time.
 ```
private string[] MediaOptions()
        {
            string[] mediaOptions;
            mediaOptions = new[] { "--network-caching=8000",
                                   "--directx-use-sysmem",
                                   "--avcodec-hw=none",
                                   "--audio-visual=visual",                                   
                                   "--effect-width=128",
                                   "--effect-height=128",
                                   "--effect-list=spectrometer", };
            return mediaOptions;
        }

public Form1()
        {
            InitializeComponent();
            Core.Initialize(Environment.CurrentDirectory + @"\libvlc\x64\");
            _libVLC = new LibVLC(MediaOptions());
            _mp = new MediaPlayer(_libVLC);
            videoView1.MediaPlayer = _mp;
            _libVLC.SetLogFile("vlclog.txt");
        }
```

**Comment by mfkl** [comment]
For support, please use stackoverflow or discord. See you there
