### ISSUE TITLE
Multiview

### ISSUE THREAD

**Issue by subh-kundu** [mfkl/libvlcsharp-samples#210]
Hi,
I want to make a program a Multiview monitor just like your RTSP Mosaic. can you help me how to add individual audio VU Meter every player any suggestion how to make easy way C# winforms application.
![Untitled-1](https://user-images.githubusercontent.com/64629942/206669212-8187498f-1df1-45d7-a725-baf1d9fb1815.jpg)

**Comment by mfkl** [comment]
Hi, the opensource samples are provided for free to the community. If you need customization work, email us for rates at dotnet@videolabs.io with your project details and timeline.

Cheers
